-- Create the waitlist table
CREATE TABLE IF NOT EXISTS public.waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    email TEXT NOT NULL,
    no_telf TEXT,
    "Keterangan" TEXT, -- Case sensitive as per your code
    UNIQUE(email)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to insert (anon key)
CREATE POLICY "Enable insert for all users" 
ON public.waitlist 
FOR INSERT 
WITH CHECK (true);

-- Create policy to allow only service role to select/view (secure)
CREATE POLICY "Enable read access for service role only" 
ON public.waitlist 
FOR SELECT 
USING (auth.role() = 'service_role');
